default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: budget_app_development
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: budget_app_test
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: budget_app_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
